# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 5a4d98638a00a6a92aa84f8fd94e56a8be5de0ac

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.socialdump@gmail.com
    password: socialdumpFEF
    protocol: smtp
    tls: true
    auth: true
    from: noreply.socialdump@gmail.com

authentication:
    xauth:
        secret: myXAuthSecret
        # Token is valid 30 minutes
        tokenValidityInSeconds: 5400

swagger:
    title: socialdump API
    description: socialdump applications and beyond!
    termsOfServiceUrl: 
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
